brew install ack
brew install chruby
brew install curl
brew install go
brew install git
brew install gitlab-runner
brew install nginx
brew install node
brew install openssl
brew install packer
brew install postgresql
brew install redis
brew install ruby-install
brew install shellcheck
brew install terraform
brew install wget
brew install yarn
brew install z
brew install zsh-completions
